### ISSUE TITLE
$SqlConnection.Close() not in a finally block

### ISSUE THREAD

**Issue by rancourt-martin** [VladDBA/PSBlitz#124]
Hi,
(amazing piece of code that saved me weeks of back and forth with a client)
fyi, I ran into the case where after completion of psblitz, connection is not closed and lingers on the sqlserver. we suspect this is caused by the $SqlConnection.Close() (or dispose) not being in  a "finally" block.

**Comment by VladDBA** [comment]
Hi @rancourt-martin ,
Thank you for the feedback!
I'm glad you find it useful.
I'll address this bug in the next release.

**Comment by VladDBA** [comment]
I've added another pair of `$SqlConnection.Close()` and `$SqlConnection.Dispose()` (there already is a `$SqlConnection.Dispose()` at the begging of the `finally` block), but the connection still remains after script PSBlitz execution finishes.
The good news is that closing the PowerShell window from which PSBlitz was executed causes the leftover connection to close immediately

**Comment by rancourt-martin** [comment]
Good stuff,

Really appreciate the feedback

Martin
__________
Martin Rancourt
514.567.1297

Le 10 nov. 2023 à 17:58, Vlad Drumea ***@***.***> a écrit :

﻿

I've added another pair of $SqlConnection.Close() and $SqlConnection.Dispose() (there already is a $SqlConnection.Dispose() at the begging of the finally block), but the connection still remains after script PSBlitz execution finishes.
The good news is that closing the PowerShell window from which PSBlitz was executed causes the leftover connection to close immediately
